// Generated by CoffeeScript 1.7.1
(function() {
  var copied, fs, k, v;

  fs = require('fs');

  copied = {};

  for (k in fs) {
    v = fs[k];
    copied[k] = v;
  }

  module.exports = copied;

}).call(this);
